config/routes.rb
Rails.application.routes.draw do
  get 'other_services/update'

  get 'gears/index'
  get 'gears/nuke'
  resources :users, only:[:new, :create, :destroy] do
    collection do
      get 'editPass/:id', action:'editPass', controller:'users', as:'editPass'
      post 'updatePass/:id', action:'updatePass', controller:'users', as:'updatePass'
    end
  end
  resources :requests do
    collection do
      get 'showmodal', to: 'requests#showmodal'
      get 'showPDF/:id',        action:'showPDF',       controller:'requests', as:'showPDF'
      get 'edOExpediture/:id',  action:'edOExpediture', controller:'requests', as:'edOExpediture'
      get 'edBenefit/:id',      action:'edBenefit',     controller:'requests', as:'edBenefit'
      get 'edOService/:id',     action:'edOService',    controller:'requests', as:'edOService'
    end
  end
  resources :people do
    collection do
      put  'updatePerson/:id',      action:'updatePerson',      controller:'people', as:'updatePerson'
      post 'addResponsable',        action:'addResponsable',    controller:'people', as:'addResponsable'
      post 'actResponsable',        action:'actResponsable',    controller:'people', as:'actResponsable'
      put  'updateResponsable/:id', action:'updateResponsable', controller:'people', as:'updateResponsable'
      post 'addRelatives',          action:'addRelatives',      controller:'people', as:'addRelatives'
      post 'addPicture',            action:'addPicture',        controller:'people', as:'addPicture'
    end
  end
  resources :relatives, only: [ :index, :update, :destroy, :edit, :create, :new ]
  resources :expeditures, :living_places,  :responsables, only: [ :index, :update ]
  resources :other_expeditures, :benefits, :other_services, only: [ :index, :show, :create, :destroy, :update ]
  resources :sessions, only:[:new, :create, :destroy]
  get "/login" => "sessions#new", as: "login"
  get 'welcome/index'
  delete "/logout" => "sessions#destroy", as: "logout"
  root to: 'welcome#index'
end

app/models/person.rb
class Person < ActiveRecord::Base
    mount_uploader :picture, MyPictureUploader
    has_one  :responsable, dependent: :destroy
    has_many :relatives,   dependent: :destroy
    has_one  :LivingPlace, dependent: :destroy
    has_many :Expediture,  dependent: :destroy
    has_many :Benefit,     dependent: :destroy
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy, :updatePerson, :showPDF]

  def index
    @people = Person.all
  end

  def show
    @relatives = @person.relatives
  end

  def new
    @person = Person.new
    @responsable = Responsable.new
    @relative = Relative.new
  end

  def edit
    @responsable = Responsable.find_by(person_id:@person.id)
    @relative = Relative.new
  end

  def create
    @person = Person.new
    setPersonVal
    respond_to do |format|
      if @person.save
        format.json { render json: @person.as_json(only: [:id] ) }
      else
       format.html { render :new }
       format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def addPicture
    @person = Person.find_by(id:params[:person][:id])
    @person.picture = params[:person][:picture]
    respond_to do |format|
      if @person.save
        format.json { render json: @person.as_json(only: [:id] ) }
      else
       #format.html { render :new }
       format.json { render json: 'PICTURE UPLOAD FAIL', status: :unprocessable_entity }
      end
    end
  end
  
  def addResponsable
    @responsable = Responsable.new
    @responsable.Person_id = params[:person]
    @responsable.name = params[:responsable][0]
    @responsable.age= params[:responsable][1]
    @responsable.gender= params[:responsable][2]
    @responsable.civil_status= params[:responsable][3]
    @responsable.salary= params[:responsable][4]
    @responsable.address= params[:responsable][5]
    @responsable.occupation= params[:responsable][6]
    @responsable.workplace= params[:responsable][7]
    @responsable.relationship= params[:responsable][8]
    respond_to do |format|
      if @responsable.save
        format.json { render json: @responsable.as_json(only: [:id] ) }
      else
       format.html { render :new }
       format.json { render json: @responsable.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def updatePerson
    respond_to do |format|
      if @person.update(person_params)
        format.json { render json: @person.as_json(only: [:id] ), status: :ok }
      else
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def updateResponsable
    @responsable  = Responsable.find(params[:id])
    respond_to do |format|
      if @responsable.update(responsable_params)
        format.json { render json: @responsable.as_json(only: [:id] ), status: :ok }
      else
        format.json { render json: @responsable.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def addRelatives
    @relations = []
    problems = false
    respond_to do |format|
      params[:relatives].each do |r|
        @relative = Relative.new
        @relative.Person_id = params[:requester]
        @relative.name = r[1][0]
        @relative.relationship = r[1][1]
        @relative.age  = r[1][2]
        @relative.gender = r[1][3]
        @relative.scolarship = r[1][4]
        @relative.civil_status = r[1][5]
        @relative.occupation = r[1][6]
        @relative.salary = r[1][7]
        
        if @relative.save
          @relations << @relative.id
        else
          problems = true
        end
      end
      if problems
        format.json { render json: @relative.errors, status: :unprocessable_entity }
      else
        format.json { render json: @relations.as_json(only: [:id] ) }
      end
    end
  end
  # def getRelatives
  #   @relatives = Relative.where :Person_id => params[:id]
  #   byebug
  #   respond_to do |format|
  #     format.js {render :partial => 'getRelatives'}
  #   end
  # end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :age, :gender, :civil_status, :occupation, :salary, :scolarship, :address, :workplace, :current_residence, :phone, :admission_date, :birth_date, :born_place, :transportation)
    end
    def responsable_params
      params.require(:responsable).permit(:name, :age, :gender, :civil_status, :salary, :address, :occupation, :workplace, :relationship)
    end
    def setPersonVal
      @person.name = params[:person][0]
      @person.age= params[:person][1]
      @person.gender= params[:person][2]
      @person.civil_status= params[:person][3]
      @person.salary= params[:person][4]
      @person.scolarship= params[:person][5]
      @person.phone= params[:person][6]
      @person.admission_date= params[:person][7]
      @person.birth_date= params[:person][8]
      @person.transportation= params[:person][9]
      @person.address= params[:person][10]
      @person.current_residence= params[:person][11]
      @person.occupation= params[:person][12]
      @person.born_place= params[:person][13]
      @person.workplace= params[:person][14]
      @person.picture= params[:person][15]
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
  <div class='row be-round_ligth_gray'>
    <div class='container'>
        <div class='row'>
          <div class='col-xs col-md-6'>
          <% if @person.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@person.errors.count, "error") %> no se pudo guardar la informacion!:</h2>
              <ul>
              <% @person.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>      
          </div>
        </div>
      </div>
  </div>
  <div class='col-xs col-md-12'>
    <ul class="nav nav-tabs">
      <li id="person" class="active"><a href="#home" data-toggle="tab">SOLICITANTE</a></li>
      <li id="responsable"><a href="#responsables" data-toggle="tab">RESPONSABLE</a></li>
      <li id="relative"><a href="#relatives" data-toggle="tab">PARIENTES</a></li>
    </ul>
  </div>
  <div id="myTabContent" class="tab-content">
    <div class="tab-pane fade active in" id="home">
      <%= bootstrap_form_for(@person ) do |f| %>
      <div class='row be-round_ligth_gray'>
        <div class='col-xs col-md-3'>
          <img id="img_prev" src="#" width='210' height=230 />
          <%= image_tag @person.picture, class:'img-fluid card thumbnail', size:'210x230', id:'actual_picture'  %>
          <%= f.file_field :picture, label:'Foto' %>
          <%= hidden_field_tag(:person_id, @person.id) %>
        </div>
        <div class='col-xs col-md-6'>
          <%= f.text_field_with_bootstrap :name, label:'Nombre', class:'ups' %>
        </div>
        <div class='col-xs col-md-1'>
          <%= f.number_field_with_bootstrap :age, label:'Edad' %>
        </div>
        <div class='col-xs col-md-1'>
          <%= f.select_with_bootstrap :gender, [['M'],['F']] ,label:'SEXO' %>
        </div>
        <div class='col-xs col-md-2'>
          <%= f.select_with_bootstrap :civil_status,[['SOLTERO'],['CASADO'],['VIUDO(A)'],['UNION LIBRE'],['MS'],['OTRO'] ],label:'Edo. civil' %>
        </div>
        <div class='col-xs col-md-2'>
          <%= f.text_field_with_bootstrap :salary, prepend:'$' ,label:'Salario', append:'.00', class:'ups' %>
        </div>
        <div class='col-xs col-md-2'>
            <%= f.select_with_bootstrap :scolarship,[['PRIMARIA'],['SECUNDARIA'],['PREPARATORIA'],['UNIVERSIDAD'],['OTRO']]  ,label:'Escolaridad' %>
        </div>
        <div class='col-xs col-md-2'>
          <%= f.text_field_with_bootstrap :phone, label:'Telefono', class:'ups' %>
        </div>
        <div class='col-xs col-md-2'>
          <%= f.text_field_with_bootstrap :admission_date, label:'Fecha admision', class:'xdate' %>
        </div>
        <div class='col-xs col-md-2'>
          <%= f.text_field_with_bootstrap :birth_date, label:'Fecha nacimiento', class:'xdate' %>
        </div>
        <div class='col-xs col-md-6'>
          <%= f.text_field_with_bootstrap :born_place, label:'Lugar de Nacimiento' %>
        </div>
        <div class='col-xs col-md-2'>
          <%= f.select_with_bootstrap :transportation,[['PUBLICO-TAXI'],['PUBLICO-CAMION'],['TAXI/CAMION'],['PRIVADO'],['OTRO']] ,label:'Transporte' %>
        </div>
      </div>
      <div class='row be-round_ligth_gray'>
        <div class='col-xs col-md-6'>
          <%= f.text_field_with_bootstrap :address, label:'Direccion', class:'ups' %>
        </div>
        <div class='col-xs col-md-6'>
          <%= f.text_field_with_bootstrap :current_residence, label:'Residencia actual', class:'ups' %>
        </div>
      </div>
      <div class='row be-round_ligth_gray'>
        <div class='col-xs col-md-6'>
          <%= f.text_field_with_bootstrap :occupation, label:'Ocupacion', class:'ups' %>
        </div>
        <div class='col-xs col-md-6'>
          <%= f.text_field_with_bootstrap :workplace, label:'Lugar de Trabajo', class:'ups' %>
        </div>
      </div>
      <div class='row be-round_ligth_gray'>
        <div class='col-xs col-md-1'>
          <a  id="save-person" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-floppy-open"></span></a> 
          <br>
        </div>
        <div class='col-xs col-md-1'>
          <a  id="edit-person" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-pencil"></span></a> 
          <br>
        </div>
        <div class='col-xs col-md-1'>
          <a  id="update-person" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-ok-circle"></span></a>
          <br>
        </div>
        </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="responsables">
      <%= bootstrap_form_for(@responsable) do |f| %>
        <div class='row be-round_ligth_gray'>
          <div class='col-xs col-md-6'>
            <%= f.text_field_with_bootstrap :name, label:'Nombre', class:'ups' %>
            <%= hidden_field_tag(:responsable_id, @responsable.id) %>
          </div>
          <div class='col-xs col-md-1'>
            <%= f.number_field_with_bootstrap :age, label:'Edad' %>
          </div>
          <div class='col-xs col-md-1'>
            <%= f.select_with_bootstrap :gender, [['M'],['F']] ,label:'SEXO' %>
          </div>
          <div class='col-xs col-md-2'>
            <%= f.select_with_bootstrap :civil_status,[['SOLTERO'],['CASADO'],['VIUDO(A)'],['UNION LIBRE'],['MS'],['OTRO'] ],label:'Edo. civil' %>
          </div>
          <div class='col-xs col-md-2'>
            <%= f.text_field_with_bootstrap :salary, prepend:'$' ,label:'Salario', append:'.00' %>
          </div>
        </div>
        <div class='row be-round_ligth_gray'>
          <div class='col-xs col-md-6'>
            <%= f.text_field_with_bootstrap :address, label:'Direccion', class:'ups' %>
          </div>
          <div class='col-xs col-md-6'>
            <%= f.text_field_with_bootstrap :occupation, label:'Ocupacion', class:'ups' %>
          </div>
        </div>
        <div class='row be-round_ligth_gray'>
          <div class='col-xs col-md-4'>
            <%= f.text_field_with_bootstrap :workplace, label:'Lugar de Trabajo', class:'ups' %>
          </div>
          <div class='col-xs col-md-4'>
            <%= f.text_field_with_bootstrap :relationship, label:'Parentesco', class:'ups' %>
          </div>
          <div class='col-xs col-md-1'>
            <br>
            <a  id="save-responsable" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-floppy-open"></span></a>
          </div>
          <div class='col-xs col-md-1'>
            <br>
            <a  id="edit-responsable" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-pencil"></span></a>
          </div>
          <div class='col-xs col-md-1'>
            <br>
            <a  id="update-responsable" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-ok-circle"></span></a>
          </div>
        </div>
      <% end %> 
    </div>
    <div class="tab-pane fade" id="relatives">
      <%= render('form_relatives') %>
      <div class='row'>
        <div class='col-xs col-md-12'>
          <table id='relationshipTable' class="table table-striped table-hover ">
            <thead>
              <tr>
                <th>NOMBRE</th>
                <th>PARENTESCO</th>
                <th>EDAD</th>
                <th>SEXO</th>
                <th>ESCOLARIDAD</th>
                <th>EDO. CIVIL</th>
                <th>OCUPACION</th>
                <th colspan='2'></th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/people/edit.html.erb
<h1>Edicion Solicitante</h1>
<%= render 'form' %>
<div class='btn-toolbar'>
    <div class='btn-group'>
        <%= link_to 'Mostrar', @person, class:'btn btn-default' %>
        <%= link_to 'Regresar', people_path, class:'btn btn-default' %>
    </div>
</div>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Personas</h1>
<!--<table class="table table-striped table-hover ">-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>#</th>-->
<!--      <th>Column heading</th>-->
<!--      <th>Column heading</th>-->
<!--      <th>Column heading</th>-->
<!--    </tr>-->
<!--  </thead>-->
<!--  <tbody>-->
<!--    <tr>-->
<!--      <td>1</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--    </tr>-->
<!--    <tr>-->
<!--      <td>2</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--    </tr>-->
<!--    <tr class="info">-->
<!--      <td>3</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--    </tr>-->
<!--    <tr class="success">-->
<!--      <td>4</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--    </tr>-->
<!--    <tr class="danger">-->
<!--      <td>5</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--    </tr>-->
<!--    <tr class="warning">-->
<!--      <td>6</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--    </tr>-->
<!--    <tr class="active">-->
<!--      <td>7</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--      <td>Column content</td>-->
<!--    </tr>-->
<!--  </tbody>-->
<!--</table> -->
<table class="table table-striped table-hover ">
  <thead>
    <tr class='info'>
      <!--<th>Tipo</th>>-->
      <th>Nombre</th>
      <th>Edad</th>
      <!--<th>Civil status</th>-->
      <!--<th>Occupation</th>-->
      <!--<th>Salary</th>-->
      <!--<th>Scolarship</th>-->
      <!--<th>Address</th>-->
      <!--<th>Workplace</th>-->
      <!--<th>Current residence</th>-->
      <!--<th>Relationship</th>-->
      <th>Telefono</th>
      <th>Adminision</th>
      <!--<th>Birth date</th>-->
      <!--<th>Transportation</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <!--<td><%#= person.kind %></td>-->
        <td><%= person.name %></td>
        <td><%= person.age %></td>
        <!--<td><%#= person.civil_status %></td>
        <td><%#= person.occupation %></td>
        <td><%#= person.salary %></td>
        <td><%#= person.scolarship %></td>
        <td><%#= person.address %></td>
        <td><%#= person.workplace %></td>
        <td><%#= person.current_residence %></td>
        <td><%#= person.relationship %></td> -->
        <td><%= person.phone %></td>
        <td><%= person.admission_date %></td>
        <!--<td><%#= person.birth_date %></td>
        <td><%#= person.transportation %></td>-->
        <td><%= link_to person, :class=>"btn btn-default btn-md" do %>
              <%= octicon 'clippy', :height => 20 %>
            <% end %></td>
        <td><%= link_to edit_person_path(person), :class=>"btn btn-default btn-md" do %>
              <%= octicon 'pencil', :height => 20 %>
            <% end %></td>
        <td><%= link_to person, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-default btn-md"  do %>
              <%= octicon 'trashcan', :height => 20 %>
            <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Agregar Persona', new_person_path, class:'btn btn-md btn-default' %>

app/views/people/new.html.erb
<div class='row'>
    <div class='col-xs col-md-8'>
        <h1>Agregar Persona</h1>
    </div>
    <div class='col-xs col-md-3'>
        <ul class="nav nav-pills">
            <br>
            <li class="active"><a>pasos de perfil completado <span class="badge">0</span></a></li>
        </ul>
    </div>
    <div id="spinnerContainer" class="spinner col-xs col-md-1"></div>
    <!--<div id='barprog' class="progress progress-striped ">-->
    <!--  <div id='bar' class="progress-bar" style="width: 33.33%"></div>-->
    <!--</div>-->
</div>
<%= render 'form' %>
<div class='row'>
    <div class='col-xs-4 col-md-4'></div>
    <div class='col-xs col-md-4'>
        <%= link_to ' Regresar', people_path, class:'btn btn-block btn-default ionicons ion-ios-undo' %>
    </div>
</div>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<div class='btn-toolbar'>
  <div class='btn-group'>
    <%= link_to 'Editar', edit_person_path(@person), class:'btn btn-default' %>
    <%= link_to 'Regresar', people_path, class:'btn btn-default' %>
  </div>
</div>
<div class='row'>
  <div class='col-xs col-md'>
    <p><strong>Tipo persona:</strong></p>
  </div>
</div>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">SOLICITANTE</h3>
  </div>
  <div class="panel-body be-round_ligth_gray">
    <div class='row'>
      <div class='col-xs col-md-4'>
        <%= image_tag @person.picture, class:'img-rounded img-responsive', size:'210x230'   %>
      </div>
      <div class='col-xs col-md-8'>
        <div class='row'>
          <div class='col-xs col-md-6'>
            <h4><%= @person.name %></h4>
          </div>
          <div class='col-xs col-md-6'>
            <h4>Fecha de admicion: <br><%= icon('calendar') %>  <%= @person.admission_date %><br></h4>
          </div>
        </div>
        <div class='row'>
          <div class='col-xs col-md-6'>
            <p>
              <strong>Direccion</strong>
              <small><cite><%= @person.address %><i class="glyphicon glyphicon-map-marker"></i></cite></small>
              <strong>Telefono</strong><br>
              <i class="glyphicon glyphicon-phone"></i><%= @person.phone %><br>
              <strong>Edad</strong><br>
              <i class="glyphicon glyphicon-info-sign"></i><%= @person.age %> años<br>
              <strong>Genero</strong><br>
              <% if @person.gender=='M' %>
                <%= icon('male') %> Masculino
              <% else %>
                <%= icon('female') %> Femenino
              <% end %>
              <br>
              <strong>Fecha de nacimiento:</strong><br>
              <%= icon('birthday-cake') %>    <%= @person.birth_date.strftime("%d %B %Y") %><br>
              <strong>Escolaridad</strong><br>
              <%= icon('graduation-cap') %>    <%= @person.scolarship %><br>
            </p>
          </div>
          <div class='col-xs col-md-6'>
            <p>
              <strong>Residencia actual</strong><br>
              <small><cite><%= @person.current_residence %><i class="glyphicon glyphicon-map-marker"></i></cite></small>
              <strong>Estado civil</strong><br>
              <%= icon('street-view') %>   
              <% if @person.gender == 'F' &&  @person.civil_status == 'SOLTERO' %>
                SOLTERA
              <% else %>
                <%= @person.civil_status %>
              <% end %>
              <br>
              <strong>Ocupacion</strong><br>
              <%= octicon "tools", :height => 17,  :class => "right left" %>
              <%= @person.occupation %><br>
              <strong>Lugar de trabajo</strong><br>
              <i class="glyphicon glyphicon-wrench"></i><%= @person.workplace %><br>
              <strong>Salario</strong><br>
              <i class="glyphicon glyphicon-usd"></i><%= @person.salary %><br>
              <strong>Transporte</strong><br>
              <%= icon('bus') %>    <%= @person.transportation %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class='row'>
      <div class='col-xs col-md-4'>
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">RESPONSABLE</h3>
          </div>
          <div class="panel-body be-round_ligth_gray">
            <div class='row'>
              <div class='col-xs col-md-12'>
                <h4><%= @person.responsable.name %></h4>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs col-md-6 '>
                <p>
                  <strong>Edad:</strong><br>
                  <%= icon('history') %>  <%= @person.responsable.age %>
                </p>
                <p>
                  <strong>Sexo:</strong><br>
                  <% if @person.responsable.gender == 'M' %>
                    <%= icon('male') %>
                  <% else %>
                    <%= icon('female') %>
                  <% end %>
                </p>
                <p>
                  <strong>Salario:</strong><br>  
                  <%= icon('usd') %>    <%= @person.responsable.salary %>
                </p>
                <p>
                  <strong>Estado Civil:</strong><br>
                  <%= icon('street-view') %>    <%= @person.responsable.civil_status %>
                </p>
              </div>
              <div class='col-xs col-md-6'>
                <p>
                  <strong>Ocupacion:</strong><br>  
                  <%= @person.responsable.occupation %>
                </p>
                <p>
                  <strong>Relacion:</strong><br>  
                  <%= @person.responsable.relationship %>
                </p>
                <p>
                  <strong>Lugar de Trabajo:</strong><br>
                  <%= @person.responsable.workplace %>
                </p>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs col-md-12'>
                <p>
                  <strong>Direccion:</strong><br>
                  <small><cite><%= @person.responsable.address %><i class="glyphicon glyphicon-map-marker"></i></cite></small>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class='col-xs col-md-8'>
        <div class="panel panel-warning">
        <div class="panel-heading">
          <div class='row'>
            <div class='col-xs col-md-11'>
              <h3 class="panel-title">PARIENTES</h3>    
            </div>
            <div class='col-xs col-md-1'>
              <%= link_to new_relative_path(Person_id:@person), :class=>"btn btn-default btn-md"  do %>
                <%= icon('plus') %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <table id='relationships' class="table table-striped table-hover ">
            <thead>
              <tr>
                  <th>NOMBRE</th>
                  <th>PARENTESCO</th>
                  <th>EDAD</th>
                  <th>SEXO</th>
                  <th>OCUPACION</th>
                  <th colspan='2'></th>
              </tr>
            </thead>
            <tbody>
              <% @relatives.each do |relative| %>
                <tr id="<%= relative.id %>">
                  <td><%= relative.name %></td>
                  <td><%= relative.relationship %></td>
                  <td><%= relative.age %></td>
                  <td><%= relative.gender %></td>
                  <td><%= relative.occupation %></td>
                  <td><%= link_to edit_relative_path(relative) , :class=>"btn btn-default btn-md" do %>
                        <%= icon('pencil') %>
                      <% end %>
                  </td>
                  <td><%= link_to relative, method: :delete, data: { confirm: 'Borrara permanentemente el pariente desea continuar?' }, 
                          :class=>"btn btn-default btn-md", remote: true  do %>
                          <%= icon('trash') %>
                      <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      </div>
  </div>
  </div>
</div>