config/routes.rb
Rails.application.routes.draw do
  get 'other_services/update'

  get 'gears/index'
  get 'gears/nuke'
  resources :users, only:[:new, :create, :destroy] do
    collection do
      get 'editPass/:id', action:'editPass', controller:'users', as:'editPass'
      post 'updatePass/:id', action:'updatePass', controller:'users', as:'updatePass'
    end
  end
  resources :requests do
    collection do
      get 'showmodal', to: 'requests#showmodal'
      get 'showPDF/:id',        action:'showPDF',       controller:'requests', as:'showPDF'
      get 'edOExpediture/:id',  action:'edOExpediture', controller:'requests', as:'edOExpediture'
      get 'edBenefit/:id',      action:'edBenefit',     controller:'requests', as:'edBenefit'
      get 'edOService/:id',     action:'edOService',    controller:'requests', as:'edOService'
    end
  end
  resources :people do
    collection do
      put  'updatePerson/:id',      action:'updatePerson',      controller:'people', as:'updatePerson'
      post 'addResponsable',        action:'addResponsable',    controller:'people', as:'addResponsable'
      post 'actResponsable',        action:'actResponsable',    controller:'people', as:'actResponsable'
      put  'updateResponsable/:id', action:'updateResponsable', controller:'people', as:'updateResponsable'
      post 'addRelatives',          action:'addRelatives',      controller:'people', as:'addRelatives'
      post 'addPicture',            action:'addPicture',        controller:'people', as:'addPicture'
    end
  end
  resources :relatives, only: [ :index, :update, :destroy, :edit, :create, :new ]
  resources :expeditures, :living_places,  :responsables, only: [ :index, :update ]
  resources :other_expeditures, :benefits, :other_services, only: [ :index, :show, :create, :destroy, :update ]
  resources :sessions, only:[:new, :create, :destroy]
  get "/login" => "sessions#new", as: "login"
  get 'welcome/index'
  delete "/logout" => "sessions#destroy", as: "logout"
  root to: 'welcome#index'
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :person
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy, :showPDF]

  def index
    @requests = Request.all
  end

  def show
    @expediture = Expediture.find_by(person:@request.person)
    @person = @request.person
    @otherExpeditures = OtherExpediture.where(Expediture:@expediture)
    @benefits = Benefit.where(person:@request.person)
    @living = LivingPlace.find_by(person:@request.person)
    @otherservices = OtherService.where(living_place:@living)
  end

  def new
    @request = Request.new
    @expediture = Expediture.new
    @livingPlace = LivingPlace.new
  end
  
  def edit
    @person = Person.find(@request.person)
    @expediture = Expediture.find_by(person_id:@person)
    # check how more expeditures are
      @otherExpeditures = OtherExpediture.where(Expediture:@expediture)
    # check how more benefits are
      @benefits = Benefit.where(person:@request.person)
    # check how many other services
      @living = LivingPlace.find_by(person_id:@person)
      @otherServices = OtherService.where(living_place:@living)
  end

  def create
    respond_to do |format|
      @request = fillRequest(Request.new)
      if @request.save
        @expediture = fillExpeditures(Expediture.new)
        #check if has more expeditures
        if @expediture.save
          fillOtherExpediture(@expediture)
          fillBenefits()
        else
          #error saving request
        end
        #check if has benefits
        @livingPlace = fillLivigPlace(LivingPlace.new,@person)
        if @livingPlace.save
          fillOtherService(@livingPlace)
        else
          #error savign living place
        end
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
      else
        #error saving request
      end
    end
    #@request = 
    #appRdata(@request)
    
    # @request = Request.new(request_params)
    # 
    #   if @request.save
    #     format.html { redirect_to @request, notice: 'Request was successfully created.' }
    #     format.json { render :show, status: :created, location: @request }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @request.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # Mine-----------------------
    def showmodal
      respond_to do |format|
        case params[:key]
          when 'expediture'
            @otherExpediture = OtherExpediture.new
            format.html {render :partial => 'modal4expediture'}
          when 'person'
            # Dont add person search and select the person Daa!
            @persons = Person.where('name LIKE ?','%'+params[:val]+'%')
            format.html {render :partial => 'modalPSearch'}
          when 'service' #vivienda servicios
            @other_service = OtherService.new
            format.html {render :partial => 'modal4service'}
          when 'benefit' #gastos prestacin nueva
            @benefit = Benefit.new
            format.html {render :partial => 'modal4benefit'}
          when 'kind'
            format.html {render :partial => 'modal4otherKind'}
          when 'wall'
            format.html {render :partial => 'modal4wall'}
          when 'roof'
            format.html {render :partial => 'modal4roof'}
          when 'floor'
            format.html {render :partial => 'modal4floor'}
        end
      end
    end
    def showPDF
      respond_to do |format|
        format.pdf do
          
          #pdf = Prawn::Document.new
          pdf = RequestPdf.new(@request)
          send_data pdf.render, 
            filename: "reques#{@request.id}.pdf",
            type: 'application/pdf',
            disposition: 'inline'
        end
      end
    end
    
    def edOExpediture
      @otherExpediture = OtherExpediture.find(params[:id])
      respond_to do |format|
        format.js
      end
    end
    
    def edBenefit
      @benefit = Benefit.find(params[:id])
      respond_to do |format|
        format.js
      end
    end
    
    def edOService
      @otherService = OtherService.find(params[:id])
      respond_to do |format|
        format.js
      end
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:case, :rdate, :sent_by, :oriented, :service, :notes, :qualification, :person_id)
    end
    
    def fillRequest(request)
      request.case          = params[:rdata][0]
      request.rdate         = params[:rdata][1]
      request.sent_by       = params[:rdata][2]
      request.oriented      = params[:rdata][3]
      request.service       = params[:rdata][4]
      request.qualification = params[:rdata][5]
      request.notes         = params[:rdata][6]
      request.person_id     = params[:pid]
      return request
    end
    
    def fillExpeditures(expediture)
      expediture.feeding     = params[:edata][0]
      expediture.rent        = params[:edata][1]
      expediture.electricity = params[:edata][2]
      expediture.water       = params[:edata][3]
      expediture.fuel        = params[:edata][4]
      expediture.education   = params[:edata][5]
      expediture.person_id   = params[:pid]
      return expediture
    end
    
    def fillOtherExpediture(expediture)
      unless params[:oedata][0] == 'false'
        params[:oedata].each do |oe|
          otherExpediture = OtherExpediture.find(oe)
          otherExpediture.expediture_id = expediture.id
          # add code to rise error on not being able to update the info
          otherExpediture.save
        end
      end
    end
    
    def fillBenefits()
      unless params[:bdata][0] == 'false'
        params[:bdata].each do |b|
          benefit = Benefit.find(b)
          benefit.person_id = params[:pid]
          # add code to rise error on not being able to update the info
          benefit.save
        end
      end
    end
    
    def fillOtherService(livingPlace)
      unless params[:osdata][0] == 'false'
        params[:osdata].each do |o|
          otherService = OtherService.find(o)
          otherService.living_place_id = livingPlace.id
          # add code to rise error on not being able to update the info
          otherService.save
        end
      end
    end
    
    def fillLivigPlace(livingPlace,person)
      livingPlace.kind            = params[:ldata][0]
      livingPlace.wall_material   = params[:ldata][1]
      livingPlace.roof_material   = params[:ldata][2]
      livingPlace.floor_material  = params[:ldata][3]
      livingPlace.number_of_rooms = params[:ldata][4]
      livingPlace.water_service   = params[:ldata][5]
      livingPlace.ligth_service   = params[:ldata][6]
      livingPlace.has_beedroom    = params[:rooms][:beedroom]
      livingPlace.has_kitchen     = params[:rooms][:kitchen]
      livingPlace.has_dinningroom = params[:rooms][:dinningroom]
      livingPlace.has_bathroom    = params[:rooms][:bathroom]
      livingPlace.Person_id       = params[:pid]
      return livingPlace
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_modal4EdOServices.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">EDITAR SERVICIO</h4>
        </div>
        <div class="modal-body">
          <%= bootstrap_form_for(@otherService, layout: :horizontal, remote:true, :html => {id:'edOServiceCommit', format:'js'}) do |f| %>
            <%= f.text_field_with_bootstrap :name, label:'SERVICIO', label_col:'col-xs col-md-4', control_col:'col-xs col-md-8' %>
            <%= f.submit 'Guardar', class:'btn btn-md btn-primary' %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

app/views/requests/_modal4EditBenefit.js.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">EDITAR GASTO</h4>
        </div>
        <div class="modal-body">
          <%= bootstrap_form_for(@benefit, layout: :horizontal, remote:true, :html => {id:'edBenefitCommit', format:'js'}) do |f| %>
            <%= f.text_field_with_bootstrap :name,   label:'Gasto' %>
            <%= f.text_field_with_bootstrap :amount, label:'Monto', prepend:'$', append:'.00' %>
            <%= f.submit 'Guardar', class:'btn btn-md btn-primary' %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

app/views/requests/_modal4expediture.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">AGREGAR OTRO GASTO</h4>
        </div>
        <div class="modal-body">
          <%= bootstrap_form_for(@otherExpediture, layout: :horizontal, remote:true, :html => {id:'addExpeditureCommit', format:'js'}) do |f| %>
            <%= f.text_field_with_bootstrap :name,   label:'Gasto' %>
            <%= f.text_field_with_bootstrap :amount, label:'Monto', prepend:'$', append:'.00' %>
            <%= f.submit 'Guardar', class:'btn btn-md btn-primary' %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

app/views/requests/_modal4floor.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 id='newFloor' class="modal-title">AGREGAR OTRO MATERIAL DE PISO</h4>
        </div>
        <div class="modal-body">
            <form class="form-horizontal">
                <fieldset>
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="wall">Otro</label>  
                      <div class="col-md-5">
                          <input id="floor" placeholder="" class="form-control input-md badBoy" type="text">
                      </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

app/views/requests/_modal4person.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">AGREGAR PERSONA</h4>
        </div>
        <div class="modal-body">
            <%= bootstrap_form_for(@person, :html => {id:'commitAddPerson'}) do |f| %>
            <div class='row'>
              <div class='col-xs col-md-4'>
                <%= f.select_with_bootstrap :kind, [['','0'],['BENEFICIARIO','1'],['RESPONSABLE','2'],['FAMILIAR','3']], label:'Tipo persona' %>
              </div>
              <div class='col-xs col-md-8'>
                <%= f.text_field_with_bootstrap :name, label:'Nombre' %>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs col-md-4'>
                <%= f.number_field_with_bootstrap :salary, label:'Salario', prepend:'$' %>
              </div>
              <div class='col-xs col-md-8'>
                <%= f.text_field_with_bootstrap :occupation, label:'Ocupacion' %>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs col-md-2'>
                <%= f.number_field_with_bootstrap :age, label:'Edad' %>
              </div>
              <div class='col-xs col-md-2'>
                <%= f.select_with_bootstrap :gender, [['M'],['F']], label:'Sexo' %>
              </div>
              <div class='col-xs col-md-4'>
                <%= f.select_with_bootstrap :civil_status, [['SOLTERO'],['CASADO'],['UNION LIBRE'],['VIUDO'],['DIVORCIADO']], label:'Estado Civil' %>
              </div>
              <div class='col-xs col-md-4'>
                <%= f.select_with_bootstrap :scolarship, [['INCOMPLETA'],['PRIMARIA'],['SECUNDARIA']], label:'Escolaridad' %>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs-12'>
                <%= f.text_field_with_bootstrap :address, label:'Direccion' %>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs-12'>
                <%= f.text_field_with_bootstrap :workplace, label:'Lugar de Trabajo' %>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs-12'>
                <%= f.text_field_with_bootstrap :current_residence, label:'Residencia actual' %>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs col-md-3'>
                <%= f.text_field_with_bootstrap :relationship, label:'Parentesco' %>
              </div>
              <div class='col-xs col-md-4'>
                <%= f.text_field_with_bootstrap :phone, label:'Telefono' %>
              </div>
              <div class='col-xs col-md-5'>
                <%= f.text_field_with_bootstrap :transportation, label:'Transporte' %>
              </div>
            </div>
            <div class='row'>
              <div class='col-xs col-md-8'>
                <%= f.date_select_with_bootstrap :admission_date, label:'Fecha admision' %>
              </div>
              <div class='col-xs col-md-8'>
                <%= f.date_select_with_bootstrap :birth_date, label:'Fecha nacimiento' %>
              </div>
            </div>
              <%= f.submit %>
            <% end %>
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

app/views/requests/_modal4roof.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 id='newRoof' class="modal-title">AGREGAR OTRO MATERIAL DE TECHO</h4>
        </div>
        <div class="modal-body">
            <form class="form-horizontal">
                <fieldset>
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="wall">Otro</label>  
                      <div class="col-md-5">
                          <input id="roof" placeholder="" class="form-control input-md badBoy" type="text">
                      </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

app/views/requests/_modalPSearch.html.erb
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">SELECCIONAR PERSONA(S)</h4>
        </div>
        <div class="modal-body">
            <div class='row'>
                <div class='col-xs col-md-10'>
                    <form class="form-horizontal">
                        <fieldset>
                            <div class="form-group">
                              <table id='namesResultsTbl' class="table table-striped table-hover ">
                                  <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>NOMBRE</th>
                                        <th colspan='1'></th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    <% @persons.each do |person| %>
                                      <tr>
                                        <td><%= person.id %></td>
                                        <td><%= person.name %></td>
                                        <td><a class="btn btn-xs btn-info selNamebtn"><span class="glyphicon glyphicon-hand-left"></span></a></td>
                                      </tr>
                                    <% end %>
                                  </tbody>
                                </table>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

app/views/requests/_tblBene.html.erb
<h5>PRESTACIONES</h5>
<table id="tblEdBenefits" class="table table-striped table-hover">
    <thead>
        <th>Descripcion</th>
        <th>Cantidad</th>
        <th colspan=2></th>
    </thead>
    <% @benefits.each do |b| %>
    <tbody>
        <tr id="<%= b.id %>">
            <td><%= b.name %></td>
            <td align='center'><%= b.amount %></td>
            <td><%= link_to edBenefit_requests_path(b), remote:true, class:'bnt btn-xs btn-primary' do %>
                    <%= icon('pencil') %>
                <% end %>
            </td>
            <td><%= link_to b, method: :delete, remote:true, data: { confirm: 'Eliminara esta prestacion esta seguro?' }, class:'btn btn-primary btn-xs' do %>
                    <%= icon('trash-o') %>
                <% end %>
            </td>
        </tr>
    </tbody>
    <% end %>
</table>

app/views/requests/_tblOExp.html.erb
<h5>OTROS GASTOS</h5>
<table id="tblEdOExpeditures" class="table table-striped table-hover">
    <thead>
        <th>Descripcion</th>
        <th>Cantidad</th>
        <th colspan=2></th>
    </thead>
    <tbody>
        <% @otherExpeditures.each do |oe| %>
        <tr id="<%= oe.id %>" >
            <td><%= oe.name %></td>
            <td align='center'><%= oe.amount %></td>
            <td><%= link_to edOExpediture_requests_path(oe), remote:true, class:'bnt btn-xs btn-primary' do %>
                    <%= icon('pencil') %>
                <% end %>
            </td>
            <td><%= link_to oe, method: :delete, remote:true, data: { confirm: 'Eliminara esta prestacion esta seguro?' }, class:'btn btn-primary btn-xs' do %>
                    <%= icon('trash-o') %>
                <% end %>
            </td>
        </tr>
        <% end %>
        
    </tbody>
    
</table>

app/views/requests/_tblOServices.html.erb
<table  class="table table-striped table-hover">
    <thead>
        <th>Descripcion</th>
        <th colspan=2></th>
    </thead>
    <tbody>
        <% @otherServices.each do |os| %>
            <tr id="<%= os.id %>">
                <td><%= os.name %></td>
                <td><%= link_to edOService_requests_path(os), remote:true, class:'bnt btn-xs btn-primary' do %>
                        <%= icon('pencil') %>
                    <% end %>
                </td>
                <td><%= link_to os, method: :delete, remote:true, data: { confirm: 'Eliminara esta prestacion esta seguro?' }, class:'btn btn-primary btn-xs' do %>
                        <%= icon('trash-o') %>
                    <% end %>
                </td>
            </tr>
        <% end %>                                              
    </tbody>                                                  
</table>

app/views/requests/edBenefit.js.erb
$('#modal-window4Edit').html("<%= escape_javascript render(:partial => 'modal4EditBenefit') %>");
$("#modal-window4Edit").modal('show');

app/views/requests/edOExpediture.js.erb
$('#modal-window4Edit').html("<%= escape_javascript render(:partial => 'modal4EditOtherExpediture') %>");
$("#modal-window4Edit").modal('show');

app/views/requests/edOService.html.erb
$('#modal-window4Edit').html("<%= escape_javascript render(:partial => 'modal4EdOServices') %>");
$("#modal-window4Edit").modal('show');

app/views/requests/new.html.erb
<div class='row'>
    <div class='col-xs col-md-6'>
      <h1>Nueva Solicitud</h1>  
    </div>
    <div id='dudename', class='col-xs col-md-5'></div>
</div>
<%= render 'form' %>
<div class='row'>
    <div class='col-xs-4 col-md-4'></div>
    <div class='col-xs col-md-4'>
        <%= link_to ' Regresar', requests_path, class:'btn btn-block btn-default ionicons ion-ios-undo' %>        
    </div>
</div>