config/routes.rb
Rails.application.routes.draw do
  get 'other_services/update'

  get 'gears/index'
  get 'gears/nuke'
  resources :users, only:[:new, :create, :destroy] do
    collection do
      get 'editPass/:id', action:'editPass', controller:'users', as:'editPass'
      post 'updatePass/:id', action:'updatePass', controller:'users', as:'updatePass'
    end
  end
  resources :requests do
    collection do
      get 'showmodal', to: 'requests#showmodal'
      get 'showPDF/:id',        action:'showPDF',       controller:'requests', as:'showPDF'
      get 'edOExpediture/:id',  action:'edOExpediture', controller:'requests', as:'edOExpediture'
      get 'edBenefit/:id',      action:'edBenefit',     controller:'requests', as:'edBenefit'
      get 'edOService/:id',     action:'edOService',    controller:'requests', as:'edOService'
    end
  end
  resources :people do
    collection do
      put  'updatePerson/:id',      action:'updatePerson',      controller:'people', as:'updatePerson'
      post 'addResponsable',        action:'addResponsable',    controller:'people', as:'addResponsable'
      post 'actResponsable',        action:'actResponsable',    controller:'people', as:'actResponsable'
      put  'updateResponsable/:id', action:'updateResponsable', controller:'people', as:'updateResponsable'
      post 'addRelatives',          action:'addRelatives',      controller:'people', as:'addRelatives'
      post 'addPicture',            action:'addPicture',        controller:'people', as:'addPicture'
    end
  end
  resources :relatives, only: [ :index, :update, :destroy, :edit, :create, :new ]
  resources :expeditures, :living_places,  :responsables, only: [ :index, :update ]
  resources :other_expeditures, :benefits, :other_services, only: [ :index, :show, :create, :destroy, :update ]
  resources :sessions, only:[:new, :create, :destroy]
  get "/login" => "sessions#new", as: "login"
  get 'welcome/index'
  delete "/logout" => "sessions#destroy", as: "logout"
  root to: 'welcome#index'
end

app/models/benefit.rb
class Benefit < ActiveRecord::Base
  belongs_to :person
  
  HUMANIZED_ATTRIBUTES = {
    :amount => 'Cantidad'
  }
  
  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end
  
  validates :amount, presence: { message: "no puede estar en blanco" }
end

app/models/expediture.rb
class Expediture < ActiveRecord::Base
  belongs_to :person
  has_many :OtherExpediture, dependent: :destroy
end

app/models/living_place.rb
class LivingPlace < ActiveRecord::Base
  belongs_to :person
  has_many :OtherService, dependent: :destroy
end

app/models/other_expediture.rb
class OtherExpediture < ActiveRecord::Base
  belongs_to :Expediture
  HUMANIZED_ATTRIBUTES = {
  	:name => 'Gasto',
  	:amount => 'Monto'
  }
  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end
  validates :name, :amount, presence: { message: "los datos, no puede estar en blanco" }
end

app/models/other_service.rb
class OtherService < ActiveRecord::Base
  belongs_to :living_place
  HUMANIZED_ATTRIBUTES = { :name => 'Servicio' }
  def self.human_attribute_name(attr, options = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end
  validates :name, presence: { message: "los datos, no puede estar en blanco" }
end

app/models/person.rb
class Person < ActiveRecord::Base
    mount_uploader :picture, MyPictureUploader
    has_one  :responsable, dependent: :destroy
    has_many :relatives,   dependent: :destroy
    has_one  :LivingPlace, dependent: :destroy
    has_many :Expediture,  dependent: :destroy
    has_many :Benefit,     dependent: :destroy
end

app/models/relative.rb
class Relative < ActiveRecord::Base
  belongs_to :Person
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :person
end

app/models/responsable.rb
class Responsable < ActiveRecord::Base
  belongs_to :Person
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  def index
    @phantomOServices = OtherService.where(living_place:nil)
    @phantomBenefits = Benefit.where(person_id:nil)
    @phantomOExpeditures = OtherExpediture.where(expediture_id:nil)
  end
  
  def nuke
    OtherService.where(living_place:nil).destroy_all
    Benefit.where(person_id:nil).destroy_all
    OtherExpediture.where(expediture_id:nil).destroy_all
    respond_to do |format|
      format.html {render :index, notice: 'unlinked data successfully finished.'}
    end
  end
end

app/controllers/other_expeditures_controller.rb
class OtherExpedituresController < ApplicationController
  before_action :set_other_expediture, only: [:show, :update, :destroy]
  def index
    @other_expeditures = OtherExpediture.all
  end
  
  def show
  end
  
  def create
    @other_expediture = OtherExpediture.new(other_expediture_params)
    respond_to do |format|
      if @other_expediture.save
        format.js 
      else
        format.js   { render :createFail }
        format.json { render json: @other_expediture.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @other_expediture.destroy
    respond_to do |format|
      format.js
    end
  end
  
  def update
    respond_to do |format|
      if @other_expediture.update(other_expediture_params)
        @otherExpeditures = OtherExpediture.where(expediture_id:@other_expediture.expediture_id)
        format.js 
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_other_expediture
      @other_expediture = OtherExpediture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def other_expediture_params
      params.require(:other_expediture).permit(:name, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/benefits_helper.rb
module BenefitsHelper
end

app/helpers/expeditures_helper.rb
module ExpedituresHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/other_expeditures_helper.rb
module OtherExpedituresHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/other_expeditures/_link2DeleteOExpediture.html.erb
<%= link_to @other_expediture, method: :delete, remote:true, data: { confirm: 'Eliminara este servicio esta seguro?' }, class:'btn btn-danger btn-xs' do %>
    <%= icon('trash-o') %>
<% end %>

app/views/other_expeditures/create.js.erb
$('#modal-window2').modal('hide');
$('#otherExpedituresTable tbody').append("<tr id='<%=  @other_expediture.id %>'>"+
"<td><%= @other_expediture.name %></td>"+
"<td>$<%= @other_expediture.amount %></td>"+
"<td align='center'><%= escape_javascript render(:partial => 'link2DeleteOExpediture') %></td></tr>");



//$('#otherExpedituresTable tbody').append("<tr><td><%= @other_expediture.name %></td><td>"+
//    "$ <%= @other_expediture.amount %></td>"+
//    "<td><a href='/other_expeditures/<%= @other_expediture.id %>' data-method='delete' class='btn btn-sm btn-danger' rel='nofollow' data-remote='true'><span class='glyphicon glyphicon-trash'></span></a></td>"+
//    "<td style='display:none;'><%= @other_expediture.id %></td></tr>")
$('#otherExpedituresTable').show();

app/views/other_expeditures/createFail.js.erb
<% @other_expediture.errors.full_messages.each do |m| %>
    alert("<%= m %>");
<% end %>

app/views/other_expeditures/destroy.js.erb
$("#<%= @other_expediture.id %>").remove();

app/views/other_expeditures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Other Expeditures</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @other_expeditures.each do |other_expediture| %>
      <tr>
        <td><%= link_to 'Show', other_expediture %></td>
        <td><%= link_to 'Edit', edit_other_expediture_path(other_expediture) %></td>
        <td><%= link_to 'Destroy', other_expediture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Other expediture', new_other_expediture_path %>

app/views/other_expeditures/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_other_expediture_path(@other_expediture) %> |
<%= link_to 'Back', other_expeditures_path %>

app/views/other_expeditures/update.js.erb
$("#modal-window4Edit").modal('hide');
$(".exp table").remove();
$(".exp").html("<%= escape_javascript render(:partial => 'requests/tblOExp') %>");